name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install server dependencies
      run: npm ci --workspace server
    
    - name: Install web dependencies
      run: npm ci --workspace web
    
    - name: Run TypeScript checks
      run: npm run type-check
    
    - name: Run server tests
      run: npm run test --workspace server
    
    - name: Build server
      run: npm run build --workspace server
    
    - name: Build web
      run: npm run build --workspace web

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit
      run: |
        npm audit --audit-level=moderate
        npm audit --workspace server --audit-level=moderate
        npm audit --workspace web --audit-level=moderate

  docker:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker images
      run: |
        docker build -f server/Dockerfile -t shopify-bulk-buddy-server .
        docker build -f web/Dockerfile -t shopify-bulk-buddy-web .
